# site settings
title: Cristian Bassan
subtitle: Maker
email: cris_ba10@hotmail.com
description: Ingeniero Electromecánico
baseurl: "/portfolio" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
street_address: 
city: Resistencia
state: Chaco
zip_code: 3500
country: Argentina
phone: +54 362-4668509

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub:
  GitLab:
  Google-Plus:
  Instagram: https://www.instagram.com/bassancristian/
  LinkedIn:
  Twitter:
  Whatsapp: https://wa.me/543624668509
  Slack:

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
